### ISSUE TITLE
Delbydel

### ISSUE THREAD

**Issue by jorgenRM** [helseprofil/norgeo#71]
We are about to see if KHfunctions can handle 8-digit codes for Delbydel (like Oslo uses).

If it can't, what are the alternatives? 

Could we establish our own 6-digit codes for Delbydel? We know that KHfunctions handles 6-digit codes (like for Bydel). However, potential 6-digit codes for DElbydel must not overlap with the Bydel-codes, but rather be like 000001, 000002, etc..

**Comment by ybkamaleri** [comment]
This issue will be more appropriate in `KHfunctions` repo.
