### ISSUE TITLE
track_change(): change table does not exist for given year

### ISSUE THREAD

**Issue by jonasrekdalmathisen** [helseprofil/norgeo#75]
When running track_change(), the request to pull data from SSB fails. The reason is 'Change table for kommune doesn't exist. From 2019-01-01 to 2020-01-02'. It existed a few hours ago. It may be due to changes in SSB tables.

 ![image](https://user-images.githubusercontent.com/78446430/205932762-a29615fd-66cd-485e-ad71-d921df77a9c5.png)

**Comment by ybkamaleri** [comment]
`track_change` will only track code change ie. not change of municipality names. The time period obviously has no changes to the municipality codes. 

[https://www.ssb.no/klass/klassifikasjoner/131/versjon/1860/endringer](https://www.ssb.no/klass/klassifikasjoner/131/versjon/1860/endringer) and in 2020 has only change in name [https://www.ssb.no/klass/klassifikasjoner/131/versjon/1846/endringer](https://www.ssb.no/klass/klassifikasjoner/131/versjon/1846/endringer)

But I agree the feedback might misleading.. it keeps trying to connect despite there is not table for municipality code change. This can be done better.
